robot_base_frame: base_link

transform_tolerance: 0.5
track_unknown: false
robot_radius: 0.30
inflater:
  robot_radius: 0.30
  inflation_radius: 0.9
  cost_scaling_factor: 15.0

# Obstacles are defined in robot folders
